server:
  port: 8080
spring:
  application:
  name: spring redis mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-redis-mysql?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    ssl: false

logging:
  level:
    com:
      a3fun:
        springredismysql:
          mapper: debug
